[ballerinax.health.fhirr4]
analyticsEnabled=true
analyticsRequiredAttributes = ["fhirUser", "client_id", "iss"]
# OpenSearch configuration
analyticsServerUrl="http://localhost:9200/patient_access/_doc" # Opensearch format: <hostname>/<index>/_doc
analyticsServerUsername="admin"
analyticsServerPassword="Strong@pass@432"
# moreInfo service configuration
analyticsMoreInfoRequired = true
analyticsMoreInfoUrl = "http://localhost:8082/more_info"
analyticsMoreInfoUsername = "admin"
analyticsMoreInfoPassword = "MoreInfo@987"
